baseURL = 'https://workany.jp/blog/'
publishDir = "docs/blog"
languageCode = 'ja-JP'
title = 'WorkAnyLAB'
theme = "hugo_theme_robust"

hasCJKLanguage = true
summaryLength = 140

titleLength = 30

pluralizeListTitles = false #複数形削除


[params]
description = "WorkAnyLAB（ワークエニーラボ）は副業・フリーランスの方々や自由な働き方を希望する方々に向けて様々な知識や情報を発信する働き方サポートメディアです。"
subtitle = "副業・フリーランスに関する様々な知識や情報を発信するメディア"
dateformat = "2006年1月2日" #15:04:05 Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "'Noto Sans JP','Hiragino Kaku Gothic ProN','ヒラギノ角ゴ ProN W3','ヒラギノ角ゴ W3','Hiragino Sans',Meiryo, メイリオ, 'MS PGothic', arial, helvetica, sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.

enableHighlight = true # highlight.js option

enableGitInfo = true

twittersite = "@WorkAnyPRO"

defaultAuthor = "デフォルトユーザー"
[params.authors]
  [params.authors.moriharu]
     name      = "もりはる"
     bio       = "副業・複業・パラレルワーク・フリーランスなど、自由な働き方に関する情報を届けるメディア「はたらく探求部」(WorkAnyLABの旧メディア)を立ち上げ、 現在は教育系NPO法人のwebマガジン編集を担当。"
     pic       = "/blog/images/author/moriharu.jpg"
     alt       = "もりはるの写真"

   [params.authors.nomotokazuki]
      name      = "野本一貴"
      bio       = "フリーランスの英日翻訳者、Webライターとして活動中。得意なジャンルは投資、クレジットカード、インバウンドなど。丁寧な翻訳、わかりやすいライティングを心がけています。"
      pic       = "/blog/images/author/nomotokazuki.png"
      alt       = "野本一貴の写真"

    [params.authors.toshiyu]
       name      = "Toshiyu"
       bio       = "電力関連の仕事に13年従事、その後インドネシアに移住して一年のほとんどを海外で過ごす。現在はライターとしてフリーランス・副業・複業に関する記事を執筆。自由な働き方に挑戦する読者へ役立つ情報の発信を目指しています。"
       pic       = "/blog/images/author/toshiyu.jpeg"
       alt       = "Toshiyuの写真"

[params.pickups]
  [params.pickups.1]
    id = "452" #案件idを入れる
    title = "3D空間に対して、ギミックを設置するUnityエンジニアを大募集！" #案件タイトルを入れる
    occupation = "エンジニア" #職種を入れる
    reward = "2,000 〜 3,000 円／時" #報酬を入れる
    reward_consultation = "" #要相談の場合はyesを入れる
    time = "3 〜 5" #日数を入れる
    time_consultation = "" #要相談の場合はyesを入れる
    day = "4 〜 8 " #時間を入れる
    day_consultation = "yes" #要相談の場合はyesを入れる

  [params.pickups.2]
    id = "446" #案件idを入れる
    title = "【急募】SNSの取材スタッフ" #案件タイトルを入れる
    occupation = "編集・ライター" #職種を入れる
    reward = "1,500 〜  円／時" #報酬を入れる
    reward_consultation = "yes" #要相談の場合はyesを入れる
    time = "3 〜" #日数を入れる
    time_consultation = "yes" #要相談の場合はyesを入れる
    day = "6" #時間を入れる
    day_consultation = "yes" #要相談の場合はyesを入れる

  [params.pickups.3]
    id = "306" #案件idを入れる
    title = "【アウトソーシング(BPO)営業】課題解決に向けた提案のできる営業募集！" #案件タイトルを入れる
    occupation = "営業" #職種を入れる
    reward = "2,500 〜 3,000 円／時" #報酬を入れる
    reward_consultation = "yes" #要相談の場合はyesを入れる
    time = "1 〜 3" #日数を入れる
    time_consultation = "yes" #要相談の場合はyesを入れる
    day = "4 〜 8" #時間を入れる
    day_consultation = "yes" #要相談の場合はyesを入れる

  [params.pickups.4]
    id = "297" #案件idを入れる
    title = "人事担当募集" #案件タイトルを入れる
    occupation = "コーポレート" #職種を入れる
    reward = "100,000 〜 円／件" #報酬を入れる
    reward_consultation = "" #要相談の場合はyesを入れる
    time = "3" #日数を入れる
    time_consultation = "" #要相談の場合はyesを入れる
    day = "3" #時間を入れる
    day_consultation = "" #要相談の場合はyesを入れる


[frontmatter]
  lastmod = ':fileModTime'

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.

[taxonomies]
tags = "tags"
archives = "archives"
sections = "sections"

[related]
    includeNewer = true
    threshold = 80
    toLower = true

  [[related.indices]]
    name = "sections"
    weight = 80

  [[related.indices]]
    name = "tags"
    weight = 60

  [[related.indices]]
    name = "date"
    weight = 10

  [markup]
    [markup.tableOfContents]
      endLevel = 2
      #ordered = true
      startLevel = 2


    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
